### ISSUE TITLE
Add `--init` to automatically bootstrap configuration or add local config generation to `init`

### ISSUE THREAD

**Issue by jsoverson** [apexlang/cli#5]
Many projects that require configuration have an `--init` switch or `init` subcommand that – by default – generates a boilerplate configuration file and/or support files.

e.g. a command like this...

```shell-session
$ apex --init
Initializing new apex.yaml and schema.apexlang...
```

...would generate an `apex.yaml` (if it doesn't exist)...

```yaml
spec: schema.apexlang
generates:
  default.txt
    module: "@apexlang/codegen/html"
```

...and a `schema.apexlang` like this (if it doesn't exist).

```apexlang
namespace "project.v1"

"NewService interface for querying data"
interface NewService {
  query(id: u32) [Order]
}

"Type for Order records"
type Order {
  id: u32
  data: value
}
```
